In [26]:
import pandas as pd
import polars as pl
import seaborn as sns

# Load the dataset
diamonds = sns.load_dataset("diamonds")

In [11]:
# Create a Pandas DataFrame
df_pd = pd.DataFrame(diamonds)
df_pd

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [13]:
# Create a Polars DataFrame
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv"
df_pl = pl.read_csv(url)
df_pl

shape: (53_940, 10)
┌───────┬───────────┬───────┬─────────┬───┬───────┬──────┬──────┬──────┐
│ carat ┆ cut       ┆ color ┆ clarity ┆ … ┆ price ┆ x    ┆ y    ┆ z    │
│ ---   ┆ ---       ┆ ---   ┆ ---     ┆   ┆ ---   ┆ ---  ┆ ---  ┆ ---  │
│ f64   ┆ str       ┆ str   ┆ str     ┆   ┆ i64   ┆ f64  ┆ f64  ┆ f64  │
╞═══════╪═══════════╪═══════╪═════════╪═══╪═══════╪══════╪══════╪══════╡
│ 0.23  ┆ Ideal     ┆ E     ┆ SI2     ┆ … ┆ 326   ┆ 3.95 ┆ 3.98 ┆ 2.43 │
│ 0.21  ┆ Premium   ┆ E     ┆ SI1     ┆ … ┆ 326   ┆ 3.89 ┆ 3.84 ┆ 2.31 │
│ 0.23  ┆ Good      ┆ E     ┆ VS1     ┆ … ┆ 327   ┆ 4.05 ┆ 4.07 ┆ 2.31 │
│ 0.29  ┆ Premium   ┆ I     ┆ VS2     ┆ … ┆ 334   ┆ 4.2  ┆ 4.23 ┆ 2.63 │
│ 0.31  ┆ Good      ┆ J     ┆ SI2     ┆ … ┆ 335   ┆ 4.34 ┆ 4.35 ┆ 2.75 │
│ …     ┆ …         ┆ …     ┆ …       ┆ … ┆ …     ┆ …    ┆ …    ┆ …    │
│ 0.72  ┆ Ideal     ┆ D     ┆ SI1     ┆ … ┆ 2757  ┆ 5.75 ┆ 5.76 ┆ 3.5  │
│ 0.72  ┆ Good      ┆ D     ┆ SI1     ┆ … ┆ 2757  ┆ 5.69 ┆ 5.75 ┆ 3.61 │
│ 0.7   ┆ Very Good ┆ D     ┆ SI1     ┆ … ┆ 2757  ┆ 5.66 ┆ 5.68 ┆ 3.56 │
│ 0.86  ┆ Premium   ┆ H     ┆ SI2     ┆ … ┆ 2757  ┆ 6.15 ┆ 6.12 ┆ 3.74 │
│ 0.75  ┆ Ideal     ┆ D     ┆ SI2     ┆ … ┆ 2757  ┆ 5.83 ┆ 5.87 ┆ 3.64 │
└───────┴───────────┴───────┴─────────┴───┴───────┴──────┴──────┴──────┘

In [14]:
# Subset the Pandas DataFrame
df_pd[["cut", "price", "clarity"]]

             cut  price clarity
0          Ideal    326     SI2
1        Premium    326     SI1
2           Good    327     VS1
3        Premium    334     VS2
4           Good    335     SI2
...          ...    ...     ...
53935      Ideal   2757     SI1
53936       Good   2757     SI1
53937  Very Good   2757     SI1
53938    Premium   2757     SI2
53939      Ideal   2757     SI2

[53940 rows x 3 columns]

In [15]:
# Subset the Polars DataFrame
df_pl[["cut", "price", "clarity"]]

shape: (53_940, 3)
┌───────────┬───────┬─────────┐
│ cut       ┆ price ┆ clarity │
│ ---       ┆ ---   ┆ ---     │
│ str       ┆ i64   ┆ str     │
╞═══════════╪═══════╪═════════╡
│ Ideal     ┆ 326   ┆ SI2     │
│ Premium   ┆ 326   ┆ SI1     │
│ Good      ┆ 327   ┆ VS1     │
│ Premium   ┆ 334   ┆ VS2     │
│ Good      ┆ 335   ┆ SI2     │
│ …         ┆ …     ┆ …       │
│ Ideal     ┆ 2757  ┆ SI1     │
│ Good      ┆ 2757  ┆ SI1     │
│ Very Good ┆ 2757  ┆ SI1     │
│ Premium   ┆ 2757  ┆ SI2     │
│ Ideal     ┆ 2757  ┆ SI2     │
└───────────┴───────┴─────────┘

In [16]:
# Use select() on the Polars DataFrame
df_pl.select(["cut", "price", "clarity"])

shape: (53_940, 3)
┌───────────┬───────┬─────────┐
│ cut       ┆ price ┆ clarity │
│ ---       ┆ ---   ┆ ---     │
│ str       ┆ i64   ┆ str     │
╞═══════════╪═══════╪═════════╡
│ Ideal     ┆ 326   ┆ SI2     │
│ Premium   ┆ 326   ┆ SI1     │
│ Good      ┆ 327   ┆ VS1     │
│ Premium   ┆ 334   ┆ VS2     │
│ Good      ┆ 335   ┆ SI2     │
│ …         ┆ …     ┆ …       │
│ Ideal     ┆ 2757  ┆ SI1     │
│ Good      ┆ 2757  ┆ SI1     │
│ Very Good ┆ 2757  ┆ SI1     │
│ Premium   ┆ 2757  ┆ SI2     │
│ Ideal     ┆ 2757  ┆ SI2     │
└───────────┴───────┴─────────┘

In [17]:
# Filter the Pandas DataFrame
df_pd[df_pd["price"] > 1000]

       carat        cut color clarity  depth  table  price     x     y     z
90      0.70      Ideal     E     SI1   62.5   57.0   2757  5.70  5.72  3.57
91      0.86       Fair     E     SI2   55.1   69.0   2757  6.45  6.33  3.52
92      0.70      Ideal     G     VS2   61.6   56.0   2757  5.70  5.67  3.50
93      0.71  Very Good     E     VS2   62.4   57.0   2759  5.68  5.73  3.56
94      0.78  Very Good     G     SI2   63.8   56.0   2759  5.81  5.85  3.72
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[39416 rows x 10 columns]

In [19]:
# Filter the Polars DataFrame
df_pl.filter(df_pl["price"] > 1000)

shape: (39_416, 10)
┌───────┬───────────┬───────┬─────────┬───┬───────┬──────┬──────┬──────┐
│ carat ┆ cut       ┆ color ┆ clarity ┆ … ┆ price ┆ x    ┆ y    ┆ z    │
│ ---   ┆ ---       ┆ ---   ┆ ---     ┆   ┆ ---   ┆ ---  ┆ ---  ┆ ---  │
│ f64   ┆ str       ┆ str   ┆ str     ┆   ┆ i64   ┆ f64  ┆ f64  ┆ f64  │
╞═══════╪═══════════╪═══════╪═════════╪═══╪═══════╪══════╪══════╪══════╡
│ 0.7   ┆ Ideal     ┆ E     ┆ SI1     ┆ … ┆ 2757  ┆ 5.7  ┆ 5.72 ┆ 3.57 │
│ 0.86  ┆ Fair      ┆ E     ┆ SI2     ┆ … ┆ 2757  ┆ 6.45 ┆ 6.33 ┆ 3.52 │
│ 0.7   ┆ Ideal     ┆ G     ┆ VS2     ┆ … ┆ 2757  ┆ 5.7  ┆ 5.67 ┆ 3.5  │
│ 0.71  ┆ Very Good ┆ E     ┆ VS2     ┆ … ┆ 2759  ┆ 5.68 ┆ 5.73 ┆ 3.56 │
│ 0.78  ┆ Very Good ┆ G     ┆ SI2     ┆ … ┆ 2759  ┆ 5.81 ┆ 5.85 ┆ 3.72 │
│ …     ┆ …         ┆ …     ┆ …       ┆ … ┆ …     ┆ …    ┆ …    ┆ …    │
│ 0.72  ┆ Ideal     ┆ D     ┆ SI1     ┆ … ┆ 2757  ┆ 5.75 ┆ 5.76 ┆ 3.5  │
│ 0.72  ┆ Good      ┆ D     ┆ SI1     ┆ … ┆ 2757  ┆ 5.69 ┆ 5.75 ┆ 3.61 │
│ 0.7   ┆ Very Good ┆ D     ┆ SI1     ┆ … ┆ 2757  ┆ 5.66 ┆ 5.68 ┆ 3.56 │
│ 0.86  ┆ Premium   ┆ H     ┆ SI2     ┆ … ┆ 2757  ┆ 6.15 ┆ 6.12 ┆ 3.74 │
│ 0.75  ┆ Ideal     ┆ D     ┆ SI2     ┆ … ┆ 2757  ┆ 5.83 ┆ 5.87 ┆ 3.64 │
└───────┴───────────┴───────┴─────────┴───┴───────┴──────┴──────┴──────┘

In [20]:
# Sort the Pandas DataFrame
df_pd.sort_values(by="price", ascending=False)

       carat        cut color clarity  depth  table  price     x     y     z
27749   2.29    Premium     I     VS2   60.8   60.0  18823  8.50  8.47  5.16
27748   2.00  Very Good     G     SI1   63.5   56.0  18818  7.90  7.97  5.04
27747   1.51      Ideal     G      IF   61.7   55.0  18806  7.37  7.41  4.56
27746   2.07      Ideal     G     SI2   62.5   55.0  18804  8.20  8.13  5.11
27745   2.00  Very Good     H     SI1   62.8   57.0  18803  7.95  8.00  5.01
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43

[53940 rows x 10 columns]

In [23]:
# Sort the Polars DataFrame
df_pl.sort("price")

shape: (53_940, 10)
┌───────┬───────────┬───────┬─────────┬───┬───────┬──────┬──────┬──────┐
│ carat ┆ cut       ┆ color ┆ clarity ┆ … ┆ price ┆ x    ┆ y    ┆ z    │
│ ---   ┆ ---       ┆ ---   ┆ ---     ┆   ┆ ---   ┆ ---  ┆ ---  ┆ ---  │
│ f64   ┆ str       ┆ str   ┆ str     ┆   ┆ i64   ┆ f64  ┆ f64  ┆ f64  │
╞═══════╪═══════════╪═══════╪═════════╪═══╪═══════╪══════╪══════╪══════╡
│ 0.23  ┆ Ideal     ┆ E     ┆ SI2     ┆ … ┆ 326   ┆ 3.95 ┆ 3.98 ┆ 2.43 │
│ 0.21  ┆ Premium   ┆ E     ┆ SI1     ┆ … ┆ 326   ┆ 3.89 ┆ 3.84 ┆ 2.31 │
│ 0.23  ┆ Good      ┆ E     ┆ VS1     ┆ … ┆ 327   ┆ 4.05 ┆ 4.07 ┆ 2.31 │
│ 0.29  ┆ Premium   ┆ I     ┆ VS2     ┆ … ┆ 334   ┆ 4.2  ┆ 4.23 ┆ 2.63 │
│ 0.31  ┆ Good      ┆ J     ┆ SI2     ┆ … ┆ 335   ┆ 4.34 ┆ 4.35 ┆ 2.75 │
│ …     ┆ …         ┆ …     ┆ …       ┆ … ┆ …     ┆ …    ┆ …    ┆ …    │
│ 2.0   ┆ Very Good ┆ H     ┆ SI1     ┆ … ┆ 18803 ┆ 7.95 ┆ 8.0  ┆ 5.01 │
│ 2.07  ┆ Ideal     ┆ G     ┆ SI2     ┆ … ┆ 18804 ┆ 8.2  ┆ 8.13 ┆ 5.11 │
│ 1.51  ┆ Ideal     ┆ G     ┆ IF      ┆ … ┆ 18806 ┆ 7.37 ┆ 7.41 ┆ 4.56 │
│ 2.0   ┆ Very Good ┆ G     ┆ SI1     ┆ … ┆ 18818 ┆ 7.9  ┆ 7.97 ┆ 5.04 │
│ 2.29  ┆ Premium   ┆ I     ┆ VS2     ┆ … ┆ 18823 ┆ 8.5  ┆ 8.47 ┆ 5.16 │
└───────┴───────────┴───────┴─────────┴───┴───────┴──────┴──────┴──────┘

In [25]:
# Find the price for the 5th record in the dataset
print(df_pl[4, 6])
df_pl[4, "price"]

335